// <auto-generated />
namespace RentMovie.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class membershiptypeupdated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(membershiptypeupdated));
        
        string IMigrationMetadata.Id
        {
            get { return "201901300538277_membershiptypeupdated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
