// <auto-generated />
namespace RentMovie.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatedagainldkjfkld : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedagainldkjfkld));
        
        string IMigrationMetadata.Id
        {
            get { return "201901301429599_updatedagainldkjfkld"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
